Add `gulp-imagemin` task
AmpersandHQ/magento2-frontools pull request #5
Opened 2017-03-08 14:55 UTC by claireparker

When the task `gulp imagemin` is run, it finds all the images in the `web/images` directory within each theme in `app/design` and minifies them if possible.

* The files are minified in place
* There is a default config provided which can be overwritten by create a `imageMinConfig.json` file in the normal place in `dev/tools`.

I would have liked to add a caching task that would only attempt to minify images that are new or updated but I couldn't work out how to get it to work with frontools helper, tasks and plugins ecosystem.

I would also like to be able to print out a message after the images have finished minifying per theme.

2017-03-09 16:43 UTC, ghost requested changes

2017-03-09 16:43 UTC, jakestubbz commented on helper/imagemin.js
> +        imageMinConfig = { "optimizationLevel": 3, "progressive": true, "interlaced": true };
We don't need to do this try/catch, if you check in the `config-loader` you'll see it throws an error if the config isn't found.

We should create a .sample config in the `config/` directory with the recommended defaults, it'll get copied over to the project on `gulp setup` and if it's then manually removed the `config-loader` module will throw out the error.

2017-03-09 16:43 UTC, jakestubbz commented on helper/imagemin.js
> +        imageMinConfig = require('../helper/config-loader')('imageMinConfig.json', plugins, config);
We can go with `imagemin.json` to keep to the current naming convention used by the other config files.

2017-03-09 16:43 UTC, jakestubbz commented on helper/imagemin.js
> +          minnedImageDir = srcBase + '/web/images/';
Do you think it's worth running this on `/web/icons` too? I'm not sure how/if that'll impact the icon task... I seem to recall that gulpicon can only optimise PNGs.

2017-03-09 16:43 UTC, jakestubbz commented on helper/imagemin.js
> +        .pipe(gulp.dest(minnedImageDir));
If you want to log a message once the task is finished, you can pipe to the logger here (see L20 `helpers/css-lint.js` for an example).

2017-03-09 16:43 UTC, jakestubbz commented
>I would have liked to add a caching task

@claireparker: Have you got a plugin in mind that you'd like to use?

2017-03-10 09:00 UTC, claireparker commented on helper/imagemin.js
> +        imageMinConfig = { "optimizationLevel": 3, "progressive": true, "interlaced": true };
Aaaah I didn't realise how that it is how it works 👍

2017-03-10 09:03 UTC, claireparker commented
@jakestubbz I wanted to use plain old `gulp-cache` as in this example https://markgoodyear.com/2014/01/getting-started-with-gulp/ (go to the "Compress Images" paragraph) which I've managed to set up on projects with less complex gulp files 😑 but couldn't get it to work properly with this setup.

2017-03-10 09:20 UTC, claireparker commented on helper/imagemin.js
> +          minnedImageDir = srcBase + '/web/images/';
As to running it on different directories, I was thinking that we could run it on this directory by default and then optionally check for an argument to specify a different folder?

I've tested this on an SVG and it did manage to minify it from 4kb to 2kb! And the repo says "Minify PNG, JPEG, GIF and SVG images with imagemin"

2017-03-10 11:47 UTC, ghost approved these changes

2017-03-10 11:48 UTC, jakestubbz commented
@claireparker: Okay, cool. I'll have a read and see if I can figure out how we can plug it into frontools - it'd be useful to not have it running unless required.

2018-01-05 10:30 UTC, claireparker commented
@jakestubbz I've updated to allow a flag which provides a directory of the user's choice to minify. This means that you can do

```
gulp imagemin --dir dev/tests/backstop_data/bitmaps_reference/
```

to minify all the Backstop screenshots!

Still outstanding is adding a caching task here - currently it tries to minify everything each time the task is run.

2018-01-05 14:22 UTC, merged